### PR TITLE
PSoC 5 support

### PR DESCRIPTION
**Pull request by christof65**
via parallel interface

### CODE REVIEW

**Comment by olikraus** [comment]
na dann, versuchen wir's mal... sieht gut aus

**Comment by jasonkahana** [comment]
Is there a PSoC 5 design implementing this in I2C?

**Comment by christof65** [comment]
No, but I had a SPI implementation instead where I could make a pull request to olikraus. It is tested on a EA DOGM128-6 display.

**Comment by jasonkahana** [comment]
Do you have a PSoC project for this that you could possibly share with me?  SPI is just fine.

 

Very best wishes!

 

 

 

 

 

____________________________

Jason A. Kahana

Integrity BioSolutions, LLC

8724 Butano Ct., Suite ‘P’

San Diego, CA  92129

jason@integritybiosolutions.com

**Pull request merged**
